### ISSUE TITLE
Mapa mental Erick armando Aguilar García 

### ISSUE THREAD

**Issue by 0eeixl** [SistemasTecTlaxiaco/actividad-1-mapa-mental-0eeixl#1]
[pdf_20220907_145910_0000.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-mapa-mental-0eeixl/files/9509251/pdf_20220907_145910_0000.pdf)

**Comment by Blanca-estela-valerio-rivero** [comment]
De acuerdo a la rúbrica 13%

**Comment by josealfredo79** [comment]
Nuevamente se debe hacer un mapa mejor realizado...por favor...

**Comment by josealfredo79** [comment]
No se realizo el trabajo bajo la indicacion hace 5 dias...

**Comment by 0eeixl** [comment]
[mapa mental ds.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-mapa-mental-0eeixl/files/9569520/mapa.mental.ds.pdf)

**Comment by 0eeixl** [comment]
[mapa mental ds.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-mapa-mental-0eeixl/files/9569606/mapa.mental.ds.pdf)

**Comment by Blanca-estela-valerio-rivero** [comment]
De acuerdo a la rúbrica tiene un 15%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
